httpPort: 8090
grpcPort: 8091
imageFolder: /flair-notifications/images
grpcEndPoint: flair-engine-grpc:6565
FlairBiEndPoint: http://localhost:8002
discovery:
  eureka:
    url: ''
ssl:
  enabled: false
  caCert: certs/trustCertCollectionFile.crt
  serverCert: certs/certChainFile.crt
  serverKey: certs/privateKeyFile.key
mailService:
  serive: sendgrid
  sender: admin-vizcentric@gmail.com
  testUser: admin@vizcentric.com
  host: smtp.sendgrid.net
  port: 587
  auth :
    user: <key name>
    pass: <password>
grpc:
  auth:
    username: flair-notifications
    jwtKey: secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1
auth:
  username: flair-notifications
  jwtKey: secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1secretKey1